[pytest]
# Additional options to customize test runs:
# --headed: Run browsers with a GUI instead of headless mode (useful for debugging and visual verification)
# -v: Verbose output, providing more detailed test results
# --html=reports/report.html: Generate an HTML report saved to the specified path
# --self-contained-html: Embed all resources into the HTML report for easy sharing
addopts = --headed -v --html=test-reports/report.html --self-contained-html

# Specify the directory containing test files
# pytest will only look for tests inside the 'tests' directory.
testpaths = tests